[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Why fix the algo when you can just make it run for longer
[profile.dev]
opt-level = 3
